### PR TITLE
Record output from pre/post-link/unlink scripts

### PR DESCRIPTION
**Pull request by jakirkham**
Should make it easier to debug cases where an install or uninstall failed for some reason by including some info from the commands run.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
Should help with debugging problems like issue ( https://github.com/conda-forge/ipympl-feedstock/issues/24 ).

**Comment by jakirkham** [comment]
Would add the linter's suggestion here is incorrect as this package uses link scripts. Have raised as issue ( https://github.com/conda-forge/conda-smithy/issues/1031 ).

**Comment by jakirkham** [comment]
Thoughts @conda-forge/ipympl?

**Comment by blink1073** [comment]
LGTM, thanks!

**Pull request merged**
